console.log("Hello World! // ENGLISH");
console.log("Hola Mundo! // SPANISH");
console.log("Hola Món! // CATALAN");
console.log("Hallo Wereld // DUTCH");
console.log("Bonjour le Monde // FRENCH");
console.log("Moien Welt! // LUXEMBOURGISH");
console.log("Ciao Mondo! // ITALIAN");
console.log("Kaixo Mundua // BASQUE");
console.log("Olá Mundo // PORTUGUESE");
console.log("Saluton Mondo // ESPERANTO");
